name: 'install to IIS'
description: 'Unzips the given file and deploys it to an IIS tier'

inputs:
  file:
    description: 'The name of the file to be downloaded.'
    required: true
  target:
    description: 'Target file path.'
    required: false
  smb_source:
    description: 'Source for config files'
    required: true
  smb_source_username:
    description: 'Username for samba connection to config files'
    required: true
  smb_source_password:
    description: 'Password for samba connection to config files'
    required: true
#  token:
#    description: 'The GitHub token. Typically this will be secrets.GITHUB_TOKEN'
#    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.target }}
    - ${{ inputs.smb_source }}
    - ${{ inputs.smb_source_username }}
    - ${{ inputs.smb_source_password }}

